# Generated by Django 5.2.6 on 2025-09-24 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
        ('projects', '0004_rename_end_date_project_date_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('activity_status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('projected_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_expense', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activity_budget_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.budgetlineitem')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.objective')),
            ],
        ),
    ]
