# Generated by Django 6.0 on 2025-12-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_department_project_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
