# Generated by Django 6.0 on 2026-02-13 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('change_requests', '0002_add_canceled_status_and_cancel_reason'),
        ('projects', '0011_make_project_leader_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('REVERT', 'Revert')], max_length=10)),
                ('change_type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('OBJECTIVE', 'Objective'), ('PERSONNEL', 'Personnel'), ('BUDGET', 'Budget'), ('COMPENSATION', 'Compensation'), ('PROJECT', 'Project'), ('ROLE', 'Role'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('description', models.TextField()),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('old_state', models.JSONField(blank=True, null=True)),
                ('new_state', models.JSONField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_log_entries', to='projects.project')),
                ('related_change_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_log_entries', to='change_requests.changerequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['project', 'timestamp'], name='history_log_project_046847_idx'), models.Index(fields=['user', 'timestamp'], name='history_log_user_id_30ffb6_idx'), models.Index(fields=['change_type', 'timestamp'], name='history_log_change__7f7709_idx')],
            },
        ),
    ]
