# Generated by Django 5.2.6 on 2025-09-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_projectmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='name',
        ),
        migrations.AddField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('EXECUTIVE', 'Executive'), ('PROJECT_STAFF', 'Project Staff')], default='PROJECT_STAFF', max_length=20),
        ),
    ]
