# Generated by Django 5.2.6 on 2025-10-10 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_role_remove_user_username_user_role_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
