# Generated by Django 5.2.6 on 2025-09-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOOE', 'Maintenance and Other Operating Expenses'), ('PS', 'Personal Services'), ('CO', 'Capital Outlay')], default='MOOE', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
