# Generated by Django 5.2.6 on 2025-10-08 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_rename_dateeffective_compensation_date_effective_and_more'),
        ('personnel', '0003_alter_department_project_alter_role_name_and_more'),
        ('projects', '0006_remove_projectmembers_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetlineitem',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='compensation',
            options={'ordering': ['-date_modified']},
        ),
        migrations.AlterUniqueTogether(
            name='budgetlineitem',
            unique_together={('project', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='compensation',
            unique_together={('type', 'personnel')},
        ),
    ]
