# Generated by Django 6.0 on 2026-01-21 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0011_make_project_leader_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('ACTIVITY', 'Activity'), ('OBJECTIVE', 'Objective'), ('PERSONNEL', 'Personnel'), ('BUDGET', 'Budget'), ('COMPENSATION', 'Compensation'), ('PROJECT', 'Project'), ('ROLE', 'Role'), ('DEPARTMENT', 'Department')], max_length=20)),
                ('operation', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('description', models.TextField()),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('current_state', models.JSONField(blank=True, null=True)),
                ('proposed_changes', models.JSONField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('date_processed', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_change_requests', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_submitted'],
                'indexes': [models.Index(fields=['project', 'status'], name='change_requ_project_8c2308_idx'), models.Index(fields=['submitted_by', 'status'], name='change_requ_submitt_d812cb_idx')],
            },
        ),
    ]
