# Generated by Django 5.2.6 on 2025-10-03 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
        ('projects', '0006_remove_projectmembers_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='projects.project'),
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project'),
        ),
    ]
