# Generated by Django 5.2.6 on 2025-10-07 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_department_project_role_project'),
        ('projects', '0006_remove_projectmembers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='project',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('name', 'project')},
        ),
    ]
