# Generated by Django 5.2.6 on 2025-09-24 02:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectmember'),
        ('users', '0003_remove_role_name_role_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectMember',
            new_name='ProjectMembers',
        ),
    ]
