# Generated by Django 5.2.6 on 2025-09-30 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectpersonnel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmembers',
            name='role',
        ),
    ]
