# Generated by Django 6.0 on 2026-01-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_grant_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_leader',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
