# Generated by Django 5.2.6 on 2025-09-24 03:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
        ('projects', '0004_rename_end_date_project_date_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetlineitem',
            name='description',
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='budgetlineitem',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budgetlineitem',
            name='name',
            field=models.CharField(choices=[('MOOE', 'Maintenance and Other Operating Expenses'), ('PS', 'Personal Services'), ('CO', 'Capital Outlay')], max_length=20),
        ),
    ]
