# Generated by Django 5.2.6 on 2025-09-24 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_remove_budgetlineitem_description_and_more'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compensation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SALARY', 'Salary'), ('HONORARIA', 'Honoraria')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dateEffective', models.DateField()),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('budgetItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.budgetlineitem')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
        ),
    ]
