# Generated by Django 5.2.6 on 2025-10-07 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_compensation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensation',
            old_name='budgetItem',
            new_name='budget_item',
        ),
    ]
