# Generated by Django 5.2.6 on 2025-10-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_rename_budgetitem_compensation_budget_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='compensation',
            old_name='dateEffective',
            new_name='date_effective',
        ),
        migrations.RenameField(
            model_name='compensation',
            old_name='dateModified',
            new_name='date_modified',
        ),
    ]
