# Generated by Django 5.2.6 on 2025-10-13 08:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_projectmembers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
