# Generated by Django 5.2.6 on 2025-10-22 02:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_project_grant_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='grant_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(999999999999.99)]),
            preserve_default=False,
        ),
    ]
